/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/complaints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List complaints with filters and pagination */
        get: operations["list_complaints_api_complaints_get"];
        put?: never;
        /** Submit a complaint (validated, rate-limited, triaged, persisted) */
        post: operations["create_complaint_api_complaints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/complaints/{complaint_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one complaint */
        get: operations["get_complaint_api_complaints__complaint_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/complaints/{complaint_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Move a complaint through the status state machine */
        patch: operations["change_status_api_complaints__complaint_id__status_patch"];
        trace?: never;
    };
    "/api/meta/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List AI Triage Providers
         * @description Active provider, all known providers, and the last 20 triage outcomes
         *     (provider, latency, fallback y/n).
         */
        get: operations["get_providers_api_meta_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate complaint statistics */
        get: operations["get_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness Probe
         * @description Lightweight liveness check.
         *
         *     CRITICAL: Does NOT touch the database or Redis so it never produces false
         *     negatives under database load or transient connectivity blips.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus Metrics
         * @description Export Prometheus metrics.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness Probe
         * @description Readiness probe that checks backing infrastructure (PostgreSQL & Redis).
         *
         *     Returns 200 if all dependencies are healthy.
         *     Returns 503 naming the specific failed dependency if any check fails.
         *     Only the exception class is returned; full errors go to the logs, since
         *     driver messages can include hostnames, usernames or DSN fragments.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Category
         * @enum {string}
         */
        Category: "water" | "electricity" | "sanitation" | "roads" | "streetlights" | "other";
        /** CategoryCount */
        CategoryCount: {
            /** Category */
            category: string;
            /** Count */
            count: number;
        };
        /**
         * ComplaintCreate
         * @description Validated input payload for creating a new complaint (POST /api/complaints).
         */
        ComplaintCreate: {
            /**
             * Location
             * @description Physical location or area of the issue
             * @example Gulberg III, Main Boulevard, Block C
             */
            location: string;
            /**
             * Reporter Contact
             * @description Optional contact (email, phone) for follow-up
             * @example 03001234567
             */
            reporter_contact?: string | null;
            /**
             * Text
             * @description Full description of the municipal complaint
             * @example Bijli nahin aa rahi, transformer khrab ho gaya hai pichle teen din se.
             */
            text: string;
        };
        /**
         * ComplaintListResponse
         * @description Paginated list of complaints.
         */
        ComplaintListResponse: {
            /** Complaints */
            complaints: components["schemas"]["ComplaintResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * ComplaintResponse
         * @description Complaint object returned by GET and POST responses.
         *
         *     ``reporter_contact`` is deliberately excluded: the API has no
         *     authentication, so returning it would publish every reporter's phone or
         *     email on the public list endpoint (see ADR 0004). Enum-typed fields make
         *     the allowed values visible in OpenAPI for the typed frontend client.
         */
        ComplaintResponse: {
            /** Ai Summary */
            ai_summary: string | null;
            /**
             * Allowed Transitions
             * @description Statuses this complaint may move to next, computed by the backend's state machine. The frontend renders these; it never hardcodes them.
             */
            allowed_transitions: components["schemas"]["Status"][];
            category: components["schemas"]["Category"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Location */
            location: string;
            priority: components["schemas"]["Priority"];
            status: components["schemas"]["Status"];
            /** Text */
            text: string;
            /** Triage Latency Ms */
            triage_latency_ms: number | null;
            triaged_by: components["schemas"]["TriagedBy"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "high" | "normal" | "low";
        /** PriorityCount */
        PriorityCount: {
            /** Count */
            count: number;
            /** Priority */
            priority: string;
        };
        /** ProviderMeta */
        ProviderMeta: {
            /** Active */
            active: boolean;
            /** Description */
            description: string;
            /** Fallback Provider */
            fallback_provider?: string | null;
            /** Name */
            name: string;
            /** Timeout Seconds */
            timeout_seconds: number;
            /** Triaged By */
            triaged_by: string;
        };
        /** ProvidersResponse */
        ProvidersResponse: {
            /** Active Provider */
            active_provider: string;
            cache: components["schemas"]["TriageCacheStats"];
            /** Providers */
            providers: components["schemas"]["ProviderMeta"][];
            /** Recent Outcomes */
            recent_outcomes: components["schemas"]["TriageOutcome"][];
        };
        /**
         * StatsResponse
         * @description Aggregated statistics for GET /api/stats.
         */
        StatsResponse: {
            /** By Category */
            by_category: components["schemas"]["CategoryCount"][];
            /** By Priority */
            by_priority: components["schemas"]["PriorityCount"][];
            /** In Progress Count */
            in_progress_count: number;
            /** Open Count */
            open_count: number;
            /** Rejected Count */
            rejected_count: number;
            /** Resolved Count */
            resolved_count: number;
            /** Total Complaints */
            total_complaints: number;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "open" | "in_progress" | "resolved" | "rejected";
        /**
         * StatusUpdateRequest
         * @description Request body for PATCH /api/complaints/{id}/status.
         */
        StatusUpdateRequest: {
            /** @description Target status to transition to */
            status: components["schemas"]["Status"];
        };
        /**
         * TriageCacheStats
         * @description AI triage cache effectiveness, counted in Redis across all replicas.
         */
        TriageCacheStats: {
            /** Hit Rate */
            hit_rate: number | null;
            /** Hits */
            hits: number;
            /** Misses */
            misses: number;
        };
        /**
         * TriageOutcome
         * @description One recent triage: which provider answered, how long it took, and whether it fell back.
         */
        TriageOutcome: {
            /**
             * Complaint Id
             * Format: uuid
             */
            complaint_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Fallback */
            fallback: boolean;
            /** Latency Ms */
            latency_ms: number | null;
            /** Provider */
            provider: string;
        };
        /**
         * TriagedBy
         * @enum {string}
         */
        TriagedBy: "llm:groq" | "llm:ollama" | "rules" | "rules:fallback" | "simulated";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationErrorResponse */
        ValidationErrorResponse: {
            /** Code */
            code: string;
            /** Detail */
            detail: Record<string, never>[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_complaints_api_complaints_get: {
        parameters: {
            query?: {
                category?: components["schemas"]["Category"] | null;
                priority?: components["schemas"]["Priority"] | null;
                status?: components["schemas"]["Status"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintListResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_complaint_api_complaints_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComplaintCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_complaint_api_complaints__complaint_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                complaint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Complaint not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_status_api_complaints__complaint_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                complaint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintResponse"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Complaint not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Transition not allowed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_providers_api_meta_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersResponse"];
                };
            };
        };
    };
    get_stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
