#!/usr/bin/env bash
# Deploy one immutable build of CivicPulse to Kubernetes with the prod overlay,
# then prove it works. Used by .github/workflows/cd.yml; runnable locally.
#
#   IMAGE_SHA=<full commit sha> [BACKEND_DIGEST=sha256:...] [FRONTEND_DIGEST=sha256:...] \
#   [GROQ_API_KEY=...] [REGISTRY_USER=... REGISTRY_TOKEN=...] [CREATE_CLUSTER=1] \
#     bash scripts/cd_deploy.sh
#
# What is deployed is always `<image>:<IMAGE_SHA>`, plus `@<digest>` when a
# digest is given (ADR 0003). Never :latest. The same script with an older SHA
# is the declarative rollback.
set -euo pipefail
cd "$(dirname "$0")/.."

: "${IMAGE_SHA:?set IMAGE_SHA to the commit SHA to deploy}"
NS=civicpulse
REGISTRY=ghcr.io/includeduck/scd-civicpulse
HOST=civicpulse.localhost
PORT=8081
OVERLAY=k8s/overlays/.deploy        # generated below, never committed

step() { printf '\n==> %s\n' "$*"; }
summary() { if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then printf '%s\n' "$*" >> "$GITHUB_STEP_SUMMARY"; fi; }
curl_ingress() { curl -sS --resolve "$HOST:$PORT:127.0.0.1" "$@"; }
PY=$(command -v python3 || command -v python)

case "$IMAGE_SHA" in
  latest|*latest*) echo "Refusing to deploy '$IMAGE_SHA': deploy an immutable commit SHA (ADR 0003)" >&2; exit 2 ;;
esac

if [ "${CREATE_CLUSTER:-0}" = 1 ]; then
  step "Ephemeral cluster (k8s/k3d-cluster.yaml)"
  k3d cluster create --config k8s/k3d-cluster.yaml --wait
  kubectl apply -f k8s/k3d/traefik-config.yaml
  for _ in $(seq 1 90); do kubectl -n kube-system get ds/traefik >/dev/null 2>&1 && break; sleep 2; done
  kubectl -n kube-system rollout status ds/traefik --timeout=180s
  kubectl apply -k k8s/k3d/vpa
  kubectl -n kube-system rollout status deploy/vpa-recommender --timeout=180s
fi

step "Namespace, Secret and registry access"
kubectl create namespace "$NS" --dry-run=client -o yaml | kubectl apply -f -
# The prod overlay deletes the placeholder Secret; the real one is made here.
# An existing Secret is kept: regenerating the database password would lock
# out an already-initialised PostgreSQL.
if ! kubectl -n "$NS" get secret backend-secrets >/dev/null 2>&1 || [ -n "${POSTGRES_PASSWORD:-}" ]; then
  kubectl -n "$NS" create secret generic backend-secrets \
    --from-literal=POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(openssl rand -hex 16)}" \
    --from-literal=GROQ_API_KEY="${GROQ_API_KEY:-}" \
    --dry-run=client -o yaml | kubectl apply -f -
fi
if [ -n "${REGISTRY_TOKEN:-}" ]; then
  # GHCR packages start private: pull with the workflow's short-lived token.
  kubectl -n "$NS" create secret docker-registry ghcr-pull --docker-server=ghcr.io \
    --docker-username="${REGISTRY_USER:?REGISTRY_USER is required with REGISTRY_TOKEN}" \
    --docker-password="$REGISTRY_TOKEN" --dry-run=client -o yaml | kubectl apply -f -
  kubectl -n "$NS" patch serviceaccount default -p '{"imagePullSecrets":[{"name":"ghcr-pull"}]}'
fi

step "Pin the images: $IMAGE_SHA"
mkdir -p "$OVERLAY"
{
  echo "# Generated by scripts/cd_deploy.sh for this deploy only; not committed."
  echo "apiVersion: kustomize.config.k8s.io/v1beta1"
  echo "kind: Kustomization"
  echo "resources: [../prod]"
  echo "images:"
  echo "  - name: $REGISTRY/backend"
  echo "    newTag: \"$IMAGE_SHA\""
  if [ -n "${BACKEND_DIGEST:-}" ]; then echo "    digest: $BACKEND_DIGEST"; fi
  echo "  - name: $REGISTRY/frontend"
  echo "    newTag: \"$IMAGE_SHA\""
  if [ -n "${FRONTEND_DIGEST:-}" ]; then echo "    digest: $FRONTEND_DIGEST"; fi
  if [ -z "${GROQ_API_KEY:-}" ]; then
    # The prod overlay selects the hosted LLM, which refuses to start without
    # a key. Without one, run the deterministic rules rather than a crash loop.
    echo "patches:"
    echo "  - target: { kind: ConfigMap, name: backend-config }"
    echo "    patch: |-"
    echo "      - op: replace"
    echo "        path: /data/TRIAGE_PROVIDER"
    echo "        value: rules"
  fi
} > "$OVERLAY/kustomization.yaml"
if [ -z "${GROQ_API_KEY:-}" ]; then
  echo "No GROQ_API_KEY: TRIAGE_PROVIDER=rules for this deploy"
  summary "> No \`GROQ_API_KEY\` secret configured: this deploy triages with the keyword rules."
fi
kubectl kustomize "$OVERLAY" | grep -E "^\s+image: $REGISTRY" | sort -u
if kubectl kustomize "$OVERLAY" | grep -E "^\s+image: $REGISTRY" | grep -q ":latest"; then
  echo "Refusing: a rendered image uses :latest" >&2; exit 2
fi

step "Apply"
kubectl -n "$NS" delete job migrate --ignore-not-found   # a Job's template is immutable
kubectl apply -k "$OVERLAY"
kubectl -n "$NS" wait --for=condition=complete job/migrate --timeout=300s
kubectl -n "$NS" rollout status deploy/backend --timeout=300s
kubectl -n "$NS" rollout status deploy/frontend --timeout=180s

step "Smoke test through the Ingress (http://$HOST:$PORT)"
for _ in $(seq 1 30); do
  [ "$(curl_ingress -o /dev/null -w '%{http_code}' "http://$HOST:$PORT/api/stats" 2>/dev/null)" = 200 ] && break
  sleep 2
done
[ "$(curl_ingress -o /dev/null -w '%{http_code}' "http://$HOST:$PORT/")" = 200 ] || { echo "FAIL: / did not return 200" >&2; exit 1; }
created=$(curl_ingress -X POST "http://$HOST:$PORT/api/complaints" -H 'Content-Type: application/json' \
  -d '{"text":"Pipe burst ho gaya hai, paani sarak par beh raha hai","location":"F-8 Markaz"}' -w '\n%{http_code}')
[ "$(tail -n1 <<<"$created")" = 201 ] || { echo "FAIL: POST returned: $created" >&2; exit 1; }
id=$(sed '$d' <<<"$created" | "$PY" -c 'import json,sys; print(json.load(sys.stdin)["id"])')
[ "$(curl_ingress -o /dev/null -w '%{http_code}' "http://$HOST:$PORT/api/complaints/$id")" = 200 ] \
  || { echo "FAIL: GET of the new complaint" >&2; exit 1; }
echo "OK: / 200, /api/stats 200, POST 201, GET 200"

step "What is running"
running=$(kubectl -n "$NS" get deploy backend -o jsonpath='{.spec.template.spec.containers[0].image}')
echo "backend: $running"
case "$running" in *":$IMAGE_SHA"*) ;; *) echo "FAIL: backend is not running $IMAGE_SHA" >&2; exit 1 ;; esac
kubectl -n "$NS" get pods -o wide
kubectl -n "$NS" get hpa
summary "### Deployed \`$IMAGE_SHA\`" "" "\`$running\`" "" "Smoke test through the Ingress: \`/\` 200, \`/api/stats\` 200, POST 201, GET 200." "" '```' "$(kubectl -n "$NS" get hpa)" '```'
